on: push
jobs:
  vitest:
    timeout-minutes: 20

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
      - name: test
        run: npm run test:unit
